export const demoAttendanceRows = [
  {
    id: "ATT-001",
    name: "Rina Pratiwi",
    division: "Finance",
    date: "18 Mei 2026",
    checkIn: "08:01",
    checkOut: "17:02",
    status: "hadir",
    lateMinutes: 0,
    location: "Kantor Pusat",
  },
  {
    id: "ATT-002",
    name: "Budi Santoso",
    division: "Operasional",
    date: "18 Mei 2026",
    checkIn: "08:17",
    checkOut: "17:10",
    status: "telat",
    lateMinutes: 17,
    location: "Kantor Pusat",
  },
  {
    id: "ATT-003",
    name: "Sari Ningsih",
    division: "HR",
    date: "18 Mei 2026",
    checkIn: "-",
    checkOut: "-",
    status: "izin",
    lateMinutes: 0,
    location: "-",
  },
  {
    id: "ATT-004",
    name: "Andi Wijaya",
    division: "Sales",
    date: "18 Mei 2026",
    checkIn: "-",
    checkOut: "-",
    status: "alpa",
    lateMinutes: 0,
    location: "-",
  },
];
