export const demoAttendanceRows = [
  { id: "ATT-001", name: "Rina Pratiwi",      division: "Finance",     date: "6 Juni 2026", checkIn: "08:01", checkOut: "17:02", status: "hadir", lateMinutes: 0,  location: "Kantor Pusat" },
  { id: "ATT-002", name: "Budi Santoso",       division: "Operasional", date: "6 Juni 2026", checkIn: "08:17", checkOut: "17:10", status: "telat", lateMinutes: 17, location: "Kantor Pusat" },
  { id: "ATT-003", name: "Sari Ningsih",       division: "HR",          date: "6 Juni 2026", checkIn: "-",     checkOut: "-",     status: "izin",  lateMinutes: 0,  location: "-" },
  { id: "ATT-004", name: "Andi Wijaya",        division: "Sales",       date: "6 Juni 2026", checkIn: "-",     checkOut: "-",     status: "alpa",  lateMinutes: 0,  location: "-" },
  { id: "ATT-005", name: "Dewi Kusuma",        division: "IT",          date: "6 Juni 2026", checkIn: "08:00", checkOut: "17:15", status: "hadir", lateMinutes: 0,  location: "Remote" },
  { id: "ATT-006", name: "Fajar Nugroho",      division: "Marketing",   date: "6 Juni 2026", checkIn: "09:05", checkOut: "18:00", status: "telat", lateMinutes: 65, location: "Kantor Pusat" },
  { id: "ATT-007", name: "Hana Ramadhani",     division: "Finance",     date: "6 Juni 2026", checkIn: "07:58", checkOut: "17:00", status: "hadir", lateMinutes: 0,  location: "Kantor Pusat" },
  { id: "ATT-008", name: "Irfan Hakim",        division: "IT",          date: "6 Juni 2026", checkIn: "-",     checkOut: "-",     status: "alpa",  lateMinutes: 0,  location: "-" },
  { id: "ATT-009", name: "Joko Prasetyo",      division: "Operasional", date: "5 Juni 2026", checkIn: "08:02", checkOut: "17:05", status: "hadir", lateMinutes: 0,  location: "Kantor Pusat" },
  { id: "ATT-010", name: "Kartika Sari",       division: "HR",          date: "5 Juni 2026", checkIn: "08:35", checkOut: "17:30", status: "telat", lateMinutes: 35, location: "Kantor Pusat" },
  { id: "ATT-011", name: "Lina Marlina",       division: "Sales",       date: "5 Juni 2026", checkIn: "-",     checkOut: "-",     status: "izin",  lateMinutes: 0,  location: "-" },
  { id: "ATT-012", name: "Muhammad Rizky",     division: "Marketing",   date: "5 Juni 2026", checkIn: "07:55", checkOut: "17:00", status: "hadir", lateMinutes: 0,  location: "Remote" },
  { id: "ATT-013", name: "Nina Anggraini",     division: "Finance",     date: "5 Juni 2026", checkIn: "08:10", checkOut: "17:10", status: "hadir", lateMinutes: 0,  location: "Kantor Pusat" },
  { id: "ATT-014", name: "Oscar Maulana",      division: "IT",          date: "5 Juni 2026", checkIn: "08:00", checkOut: "17:00", status: "hadir", lateMinutes: 0,  location: "Kantor Pusat" },
  { id: "ATT-015", name: "Putri Handayani",    division: "Operasional", date: "4 Juni 2026", checkIn: "-",     checkOut: "-",     status: "alpa",  lateMinutes: 0,  location: "-" },
  { id: "ATT-016", name: "Rizal Firmansyah",   division: "HR",          date: "4 Juni 2026", checkIn: "08:22", checkOut: "17:20", status: "telat", lateMinutes: 22, location: "Kantor Pusat" },
  { id: "ATT-017", name: "Sinta Dewi",         division: "Sales",       date: "4 Juni 2026", checkIn: "08:00", checkOut: "17:00", status: "hadir", lateMinutes: 0,  location: "Kantor Pusat" },
  { id: "ATT-018", name: "Tommy Setiawan",     division: "IT",          date: "4 Juni 2026", checkIn: "-",     checkOut: "-",     status: "izin",  lateMinutes: 0,  location: "-" },
  { id: "ATT-019", name: "Uswatun Hasanah",    division: "Marketing",   date: "4 Juni 2026", checkIn: "07:59", checkOut: "17:05", status: "hadir", lateMinutes: 0,  location: "Remote" },
  { id: "ATT-020", name: "Vino Bastian",       division: "Finance",     date: "4 Juni 2026", checkIn: "09:12", checkOut: "18:00", status: "telat", lateMinutes: 72, location: "Kantor Pusat" },
  { id: "ATT-021", name: "Wulan Sari",         division: "HR",          date: "3 Juni 2026", checkIn: "08:05", checkOut: "17:00", status: "hadir", lateMinutes: 0,  location: "Kantor Pusat" },
  { id: "ATT-022", name: "Xander Pratama",     division: "IT",          date: "3 Juni 2026", checkIn: "08:45", checkOut: "18:00", status: "telat", lateMinutes: 45, location: "Kantor Pusat" },
  { id: "ATT-023", name: "Yanti Permata",      division: "Sales",       date: "3 Juni 2026", checkIn: "08:00", checkOut: "17:00", status: "hadir", lateMinutes: 0,  location: "Kantor Pusat" },
  { id: "ATT-024", name: "Zainal Abidin",      division: "Operasional", date: "3 Juni 2026", checkIn: "-",     checkOut: "-",     status: "alpa",  lateMinutes: 0,  location: "-" },
  { id: "ATT-025", name: "Rina Pratiwi",       division: "Finance",     date: "3 Juni 2026", checkIn: "08:03", checkOut: "17:00", status: "hadir", lateMinutes: 0,  location: "Kantor Pusat" },
  { id: "ATT-026", name: "Budi Santoso",       division: "Operasional", date: "3 Juni 2026", checkIn: "08:30", checkOut: "17:30", status: "telat", lateMinutes: 30, location: "Kantor Pusat" },
  { id: "ATT-027", name: "Fajar Nugroho",      division: "Marketing",   date: "3 Juni 2026", checkIn: "-",     checkOut: "-",     status: "alpa",  lateMinutes: 0,  location: "-" },
  { id: "ATT-028", name: "Hana Ramadhani",     division: "Finance",     date: "3 Juni 2026", checkIn: "07:55", checkOut: "17:00", status: "hadir", lateMinutes: 0,  location: "Kantor Pusat" },
  { id: "ATT-029", name: "Kartika Sari",       division: "HR",          date: "3 Juni 2026", checkIn: "09:20", checkOut: "18:00", status: "telat", lateMinutes: 80, location: "Kantor Pusat" },
  { id: "ATT-030", name: "Nina Anggraini",     division: "Finance",     date: "3 Juni 2026", checkIn: "-",     checkOut: "-",     status: "izin",  lateMinutes: 0,  location: "-" },
];
